### ISSUE TITLE
nginx rewrite rule

### ISSUE THREAD

**Issue by bit-rocket** [apsdehal/Link#13]
Thanks for your project.
Would please specify how to configure nginx rewrite rule ? with php7.0-fpm

**Comment by apsdehal** [comment]
Under the server block of your virtual host configuration, try adding these lines

```
location / {
  try_files $uri $uri/ /index.php?$args;
}
```

**Comment by bit-rocket** [comment]
Thanks a lot. It works.

**Comment by apsdehal** [comment]
Closing on that accord.
