### ISSUE TITLE
Link running in a subdirectory? 

### ISSUE THREAD

**Issue by spencerthayer** [apsdehal/Link#15]
I have a weird use case. I am writing an app that is mostly installed at the root of a domain, however, I want it to be flexible enough to run within a subdirectory of a domain. So I need to run link as root in both `domain.com` and `domain.com/applicationroot`. How do I do this?

**Comment by apsdehal** [comment]
It depends on your server configuration. Same code should work on both places. Did you try it?

**Comment by apsdehal** [comment]
Closing as stale.
